name: Init

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'Initial commit') }}

steps:
  - uses: actions/checkout@v2

  - name: Run a one-line script
    run: echo Hello, world!